name: qdaxpy38
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- pip>=20.3.3
- conda>=4.9.2
- jupyter
- ipython
- pip:
    - -r requirements.txt
    - -r requirements-dev.txt
    - -e .
