name: ci

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install test requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run pytests
        run: |
          pytest -vv tests
